minimumReleaseAge: 10080
minimumReleaseAgeExclude:
  - '@chemmedia/*'
  - 'knowledgeworker-embedded-asset-api'
  - 'knowledgeworker-embedded-asset-api-ui'

ignoredBuiltDependencies:
  - '@parcel/watcher'
  - 'esbuild'